apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-go-app
spec:
  selector:
    matchLabels:
      app: k8s-go-app
  template:
    metadata:
      labels:
        app: k8s-go-app
    spec:
      imagePullSecrets:
      - name: ${secret}
      containers:
      - name: k8s-go-app
        image: ${docker_server}/${registry_path}/k8s-go-app:${tag}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
