apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-go-app
spec:
  selector:
    matchLabels:
      app: k8s-go-app
  template:
    metadata:
      labels:
        app: k8s-go-app
    spec:
      containers:
      - name: k8s-go-app
        image: ${repository}/k8s-go-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
